### ISSUE TITLE
case fio_fb.py with test config fio_fb_perf.json， every test pattern will do precondition, need enhancement 

### ISSUE THREAD

**Issue by kwzhu123** [opencomputeproject/ocp-diag-autoval-ssd#12]
**1.run test case fio_fb.py with test config fio_fb_perf.json**
**2.every pattern will do precondition, make test case very long time**
    "run_definition": {
        "sequential": {
            "template": "sequential_job.fio",
            "precondition_loops": 2,
            "precondition_template": "sequential_precondition.fio",
            "args": {
                "RUNTIME": "1200s",
                "RW": ["write", "read"],
                "BLKSIZE": ["256k", "512k"],
                "IODEPTH": ["1", "4", "8", "16"],
                "NUM_JOBS": 1
            }
        },
        "random": {
            "template": "random_job.fio",
            "precondition_loops": 2,
            "precondition_template": "random_precondition.fio",
            "args": {
                "RUNTIME": "1200s",
                "RWMIX": [0, 70, 100],
                "BLKSIZE": ["256k", "512k"],
                "IODEPTH": ["1", "4", "8", "16"],
                "NUM_JOBS": ["1", "4", "8"],
                "RW": "randrw"
            }
        }

**3.every test pattern will do precondition**
![image](https://github.com/user-attachments/assets/cb741bea-c77d-4654-922d-eb7a075937b8)

**4.test log**
[test_results.log](https://github.com/user-attachments/files/16464550/test_results.log)

**Comment by aarthi-manivel** [comment]
If pre-condition is to be ignored, it can be modified in the test control file .
Just removing the below two lines from fio_fb_perf.json should suffice the need.

"precondition_loops": 2,
"precondition_template": "sequential_precondition.fio",

"precondition_loops": 2,
"precondition_template": "random_precondition.fio",

**Comment by kwzhu123** [comment]
the requirement is only do precondition first time, and repeat test other pattern without precondition due to drive already stable status, do we support it?

**Comment by aarthi-manivel** [comment]
Yes @kwzhu123 , You can just modify the control file to below to avoid precondition on every run. Here it does only one precondition on sequential job and the test progresses


```
{
    "trim_arg": {"BLKSIZE": "1G", "BLKALIGN": "1G"},
    "run_definition": {
        "sequential": {
            "template": "sequential_job.fio",
            "precondition_loops": 1,
            "precondition_template": "sequential_precondition.fio",
            "args": {
                "RUNTIME": "1200s",
                "RW": ["write", "read"],
                "BLKSIZE": ["256k", "512k"],
                "IODEPTH": ["1", "4", "8", "16"],
                "NUM_JOBS": 1
            }
        },
        "random": {
            "template": "random_job.fio",
            "args": {
                "RUNTIME": "1200s",
                "RWMIX": [0, 70, 100],
                "BLKSIZE": ["256k", "512k"],
                "IODEPTH": ["1", "4", "8", "16"],
                "NUM_JOBS": ["1", "4", "8"],
                "RW": "randrw"
            }
        }
    }
}
```
If you prefer to minimise run time , reduce the BLKSIZE to just 256k , reduce RUNTIME and as well IODEPTH and NUM_JOBS, if you prefer to test onlyon selective parameters or if you are just validating the script and not the drives

**Comment by kwzhu123** [comment]
i see， use **precondition_loops** parameter in json config can control precondition loops, this issue is invaild , help to close it
