### ISSUE TITLE
FIOSynth default build rpm name and command is fiosynth， should ocp-diag-autoval-ssd use fiosynth instead  ﻿of fb-FioSynthFlash

### ISSUE THREAD

**Issue by kwzhu123** [opencomputeproject/ocp-diag-autoval-ssd#15]
**1**
/src/autoval_ssd/lib/utils/fio/fio_synth_flash_utils.py
    @staticmethod
    def tool_setup(host) -> None:
        AutovalLog.log_info("Installing fb-FioSynthFlash")
        SystemUtils.install_rpms(host, ["fb-FioSynthFlash"])   #default  rpm name is  fiosynth 
        FioSynthFlashUtils.get_version(host)

    @staticmethod
    def get_version(host) -> None:
        out = host.run("fb-FioSynthFlash -v")   #default  command is fiosynth 
        pattern = r"\d+\.\d+\.*\d*"
        match = re.search(pattern, out)
        if match:
            version = match.group(0)
            AutovalLog.log_info("+++Running fb-FioSynthFlash version: %s" % version)

**2**
FioSynth master , build rpm name is fiosynth
sudo python3 setup.py bdist_rpm

sudo rpm -ivh fiosynth-3.6.0-1.noarch.rpm

[tcnsh@localhost dist]$ sudo rpm -qa | grep fiosynth
fiosynth-3.6.0-1.noarch

[tcnsh@localhost dist]$ fiosynth -h
usage: fiosynth [-h] -d DEVICE [-c FACTOR] -w WKLDS -f FNAME [-r DRYRUN] [-t HEALTH] [-p PREP] [-n CYCLES] [-g GETFLASH] [-s SERVERS] [-l SERVER_FILE] [-j JOB_SCALE]
                [-x] [-z] [-m MISC] [-e EXPERT] [-u USER] [-y TUNNELING] [--waf] [--lm] [--targets] [--scale-by-TB] [-v]

**Comment by manimaran1997** [comment]
Hi @kwzhu123 This issue was fixed in this commit - https://github.com/opencomputeproject/ocp-diag-autoval-ssd/commit/962368773d27dace9cbeb616026367b87e888885
